# Generated by Django 3.1.7 on 2021-03-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210326_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmark',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
