# Generated by Django 3.1.7 on 2021-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_dieticians'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticians',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
