# Generated by Django 3.1.7 on 2021-04-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_dieticians_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticians',
            name='tot_rank_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dieticians',
            name='bookmark',
            field=models.CharField(default='', max_length=20),
        ),
    ]
