# Generated by Django 3.1.7 on 2021-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210403_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieticians',
            name='bookmark',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='dieticians',
            name='tot_rank_score',
            field=models.FloatField(default=0),
        ),
    ]
