# Generated by Django 3.1.7 on 2021-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210403_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieticians',
            name='bookmark',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
