# Generated by Django 3.1.7 on 2021-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210403_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieticians',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
