# Generated by Django 3.1.7 on 2021-04-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210406_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('consulter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.dieticians')),
            ],
        ),
    ]
