# Generated by Django 3.1.7 on 2021-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='user_name',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
