# Generated by Django 3.1.7 on 2021-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210409_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='consulter',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
