# Generated by Django 3.1.7 on 2021-04-09 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210409_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
