# Generated by Django 3.1.7 on 2021-04-10 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210410_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 34, 24, 192606, tzinfo=utc)),
        ),
    ]
