# Generated by Django 3.1.7 on 2021-04-13 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210410_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='desc',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='CLOSING',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 1, 9, 4, 606902)),
        ),
    ]
