# Generated by Django 3.1.7 on 2021-04-16 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20210413_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='user_id',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='user_name',
            new_name='patient_name',
        ),
        migrations.AddField(
            model_name='appointments',
            name='opening',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 11, 46, 45, 137916)),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_response',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='CLOSING',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 11, 46, 45, 137916)),
        ),
    ]
