# Generated by Django 3.1.7 on 2021-04-16 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210416_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='CLOSING',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 12, 29, 7, 597002)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient_response',
            field=models.TextField(default='Null', max_length=300),
        ),
    ]
