# Generated by Django 3.1.7 on 2021-04-16 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20210416_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='patient_certificate',
            new_name='treatment',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='CLOSING',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 12, 43, 35, 429958)),
        ),
    ]
